# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=300, null=True)),
                ('social_security_number', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.TextField()),
                ('zip_code', models.PositiveSmallIntegerField()),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_birth', models.DateField()),
                ('home_phone', models.CharField(blank=True, max_length=300, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=300, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
